development:
  host: localhost
  adapter: postgresql
  encoding: UTF-8
  database: clicoubeleza_development
  pool: 5
  username: postgres
  password: 123

test:
  host: localhost
  adapter: postgresql
  encoding: UTF-8
  database: clicoubeleza_test
  pool: 5
  username: postgres
  password: 123

staging:
  host: localhost
  adapter: postgresql
  encoding: UTF-8
  database: clicoubeleza_staging
  pool: 5
  username: postgres
  password: 123

production:
  host: localhost
  adapter: postgresql
  encoding: UTF-8
  database: clicoubeleza_production
  pool: 5
  username: postgres
  password: 123